export const FARM_REPOSITORY = Symbol('FARM_REPOSITORY');
export const FARM_ROLE_PERMISSION_REPOSITORY = Symbol('FARM_ROLE_PERMISSION_REPOSITORY');
export const FARM_ROLE_REPOSITORY = Symbol('FARM_ROLE_REPOSITORY');
export const FARM_USER_REPOSITORY = Symbol('FARM_USER_REPOSITORY');
export const FARM_USER_USAGE_REPOSITORY = Symbol('FARM_USER_USAGE_REPOSITORY');
