name: farm-flow

services:
  postgres:
    image: postgres:16
    container_name: farm-flow-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ../docker/farm-flow/postgres/:/var/lib/postgresql/data
    ports:
      - 54325:5432
    restart: unless-stopped
    networks:
      - farm-flow

  valkey:
    image: valkey/valkey:latest
    container_name: farm-flow-valkey
    volumes:
      - ../docker/farm-flow/valkey:/data
    ports:
      - 6370:6379
    restart: unless-stopped
    networks:
      - farm-flow

networks:
  farm-flow:
    driver: bridge
