export const INVITATION_FARM_REPOSITORY = Symbol('INVITATION_FARM_REPOSITORY');
export const INVITATION_FARM_USER_REPOSITORY = Symbol('INVITATION_FARM_USER_REPOSITORY');
export const INVITATION_EMAIL_QUEUE = Symbol('INVITATION_EMAIL_QUEUE');
export const INVITATION_ROLE_REPOSITORY = Symbol('INVITATION_ROLE_REPOSITORY');
export const INVITATION_STORE = Symbol('INVITATION_STORE');
export const INVITATION_USER_REPOSITORY = Symbol('INVITATION_USER_REPOSITORY');
