export const AUTH_ACCESS_TOKEN_ISSUER = Symbol('AUTH_ACCESS_TOKEN_ISSUER');
export const AUTH_FARM_USER_REPOSITORY = Symbol('AUTH_FARM_USER_REPOSITORY');
export const AUTH_PASSWORD_HASHER = Symbol('AUTH_PASSWORD_HASHER');
export const AUTH_REFRESH_TOKEN_STORE = Symbol('AUTH_REFRESH_TOKEN_STORE');
export const AUTH_ROLE_PERMISSION_REPOSITORY = Symbol('AUTH_ROLE_PERMISSION_REPOSITORY');
export const AUTH_USER_REPOSITORY = Symbol('AUTH_USER_REPOSITORY');
