export const ROLE_FARM_USER_REPOSITORY = Symbol('ROLE_FARM_USER_REPOSITORY');
export const ROLE_PERMISSION_REPOSITORY = Symbol('ROLE_PERMISSION_REPOSITORY');
export const ROLE_REPOSITORY = Symbol('ROLE_REPOSITORY');
