export const ATTENDANCE_FARM_USER_REPOSITORY = Symbol('ATTENDANCE_FARM_USER_REPOSITORY');
export const ATTENDANCE_REPOSITORY = Symbol('ATTENDANCE_REPOSITORY');
export const ATTENDANCE_QR_CODE_STORE = Symbol('ATTENDANCE_QR_CODE_STORE');
